# base name of OCP users that will have access to their corresponding API Mgmt related projects
ocp_user_name_base: ocp


# initial base name of 3scale API administrator of each tenant; ie: api1, api2, api3 ...
#
# default is "api" so that it is intentionally different than the user names commonly found in the following OCP OAuth providers:
#   1)  htpassword:  base name is commonly "user"
#   2)  github.com:gpe-mw-ansible-org/rh-sso-multi-realm : base name is commonly "ocp"
#
# If afterwards 3scale Admin Portal is configured to leverage one of the two OCP OAuth providers, this change will be evident because the admin user names will have changed
#   ie;  from api1  to ocp1
tenant_admin_user_name_base: api
tenantAdminPasswd: admin

use_padded_tenant_numbers: true

create_gws_with_each_tenant: "true"

tenant_api_gw_template_url: "https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/{{ threescale_version }}/apicast-gateway/apicast.yml"
tenant_api_wildcard_gw_template_url: "https://raw.githubusercontent.com/gpe-mw-training/3scale_onpremise_implementation_labs/master/resources/rhte/3scale-wc-router.yml"

adminEmailUser: changeme
adminEmailDomain: "changeme.com"

tenant_output_dir: "{{new_app_output_dir}}/tenants_{{API_MANAGER_NS}}"
tenant_provisioning_log_file: "tenant_provisioning.log"
start_tenant: 1
end_tenant: 1
tenant_loop_delay: 15
tenant_provisioning_results_file: "tenant_info_file_{{start_tenant}}_{{end_tenant}}.txt"

# TO_DO:  Must current be set to true
#   Otherwise, the following exception will be thrown in API gateway:
#       failed to get list of services: invalid status: 403 (Forbidden) url: http://system-master.3scale-mt-api0:3000/admin/api/services.json, context: ngx.timer
#       configuration request sent: http://system-master.3scale-mt-api0:3000/admin/api/nginx/spec.json, context: ngx.timer
tenant_reference_external_api_mgmt_routes: "true"

# AAD rhte-oc-cluster-vms passes this variable.
# tenant gateway project (if provisioned) should be additionally owned by value of this variable
ocp_username: developer

