---
- name: post_workload Tasks Complete
  debug:
    msg: "Pre-Software checks completed successfully - Removed"


#####       TENANT Management       #######

- name: Tenant removal starting
  debug:
    msg:
      - "tenant_output_dir:  {{tenant_output_dir}}"
      - "tenant_provisioning_log_file = {{tenant_output_dir}}/{{tenant_provisioning_log_file}}"
      - "tenant_provisioning_results_file = {{tenant_output_dir}}/{{tenant_provisioning_results_file}}"
      - "start and end tenants = {{start_tenant}}  {{end_tenant}}"
      - "create API Gateways for each tenant = {{create_gws_with_each_tenant}}"

##############################################


- name: Remove user Quota - oc delete clusterresourcequota  "clusterquota-{{OCP_AMP_ADMIN_ID}}"
  shell: oc delete clusterresourcequota clusterquota-{{OCP_AMP_ADMIN_ID}}
  ignore_errors: true

- name: Remove user Project
  shell: "oc delete project {{API_MANAGER_NS}}"

- name: post_workload Tasks Complete
  debug:
    msg: "Post-Software checks completed successfully - Removed"
