apiVersion: v1
kind: LimitRange
metadata:
  name: "{{API_MANAGER_NS}}-core-resource-limits"
  namespace: "{{API_MANAGER_NS}}"
spec:
  limits:
  - default:
      cpu: 500m
      memory: 128Mi
    defaultRequest:
      cpu: 250m
      memory: 64Mi
    max:
      memory: 6Gi
    min:
      memory: 10Mi
    type: Container
  - max:
      memory: 12Gi
    min:
      memory: 6Mi
    type: Pod
