apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ service }}
spec:
  host: {{ route_hostname }}
  port:
    targetPort: proxy
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ service }}
  wildcardPolicy: None
