---

# create project

- name: create project {{ namespace }}
  oc_project:
    state: present
    oc_binary: "{{ openshift_cli }}"
    name: "{{ namespace }}"

- name: assign user {{ project_admin }} as project admin in {{ namespace }}
  oc_adm_policy_user:
    state: present
    oc_binary: "{{ openshift_cli }}"
    resource_kind: role
    user: "{{ project_admin }}"
    namespace: "{{ namespace }}"
    rolebinding_name: "{{ project_admin }}-admin"
    resource_name: admin
  when: >
    project_admin is defined and
    project_admin is not none and
    project_admin|trim() != ""

- name: annotate project {{ namespace }}
  oc_project_annotate:
    state: present
    oc_binary: "{{ openshift_cli }}"
    name: "{{ namespace }}"
    annotations: "{{ project_annotations }}"
    debug: True
  when: >
    project_annotations is defined and
    project_annotations is not none and
    project_annotations|trim() != ""
