---

amp_master_passwd: master
master_access_token: wtqhhsly

default_tenant_name: "t1"
default_tenant_admin_passwd: admin
default_tenant_access_token: 3832cnj371woiduh

# smtp
smtp_host: "smtp.sendgrid.net"
smtp_port: 587
smtp_authentication: plain
smtp_userid: changeme
smtp_passwd: changeme
smtp_domain: "redhat.com"

# CMS
use_rwo_for_cms: false

RESUME_CONTROL_PLANE_GWS: true

build_status_retries: 20
build_status_delay: 20

deploy_status_retries: 15
deploy_status_delay: 20

# Output and log files to be added to invokers home directory
new_app_output_dir: "{{ lookup('env','HOME') }}/provisioning_output/{{ ocp_domain }}"
new_app_output: "{{new_app_output_dir}}/{{API_MANAGER_NS}}-out.log"

######  OLD #####
is_shared_cluster: false

ocp_user_groups:
  - OPENTLC-PROJECT-PROVISIONERS

limit_range_changes_needed: true

# dedicated API Manager
quota_requests_cpu_dedicated: 4
quota_limits_cpu_dedicated: 12            # Safe to over-provision on CPU; at any given time, API Manager for test purposes really only needs about 4 CPU total
quota_requests_memory_dedicated: '16Gi'
quota_limits_memory_dedicated: '24Gi'

# shared API Manager
quota_requests_cpu_shared: 20
quota_limits_cpu_shared: 30
quota_requests_memory_shared: '20Gi'
quota_limits_memory_shared: '30Gi'


quota_configmaps: 15
quota_pods: 30
quota_persistentvolumeclaims: 10
quota_services: 150
quota_secrets: 150
quota_requests_storage: 40Gi

#################

