apiVersion: v1
kind: LimitRange
metadata:
  name: "{{api_control_plane_project}}-core-resource-limits"
  namespace: "{{api_control_plane_project}}"
spec:
  limits:
  - default:
      cpu: 500m
      memory: 128Mi
    defaultRequest:
      cpu: 250m
      memory: 64Mi
    max:
      memory: 6Gi
    min:
      memory: 10Mi
    type: Container
  - max:
      memory: 12Gi
    min:
      memory: 6Mi
    type: Pod
