---

- name: Deploy threescale apimanager
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true

  tasks:
    - set_fact:
        namespace: "{{ API_MANAGER_NS }}"
        work_dir_name: "{{ API_MANAGER_NS }}"
        project_admin: "{{ OCP_AMP_ADMIN_ID }}"
    - include_role:
        name: ../roles/apimanager
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/apimanager
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"
